[config]
skip_git_env_info = true

[tasks.test]
clear = true
command = "cargo"
args = ["make", "test"]
cwd = "hackrf-web"

[tasks.build]
clear = true
command = "cargo"
args = ["make", "build"]
cwd = "hackrf-web"
